# Generated by Django 4.2.20 on 2025-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='installment',
            name='payed_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
