# Generated by Django 4.2.20 on 2025-09-19 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_installment_payed_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfranchise',
            name='registration_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
