# Generated by Django 4.2.20 on 2025-09-19 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_userfranchise_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
