# Generated by Django 4.2.20 on 2025-09-19 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_batch_batch_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.IntegerField(unique=True),
        ),
    ]
