# Generated by Django 4.2.20 on 2025-09-19 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_batch_batch_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfranchise',
            name='registration_number',
        ),
        migrations.AlterField(
            model_name='batch',
            name='batch_no',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
