# Generated by Django 4.2.20 on 2025-09-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_userfranchise_registration_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch_no',
        ),
    ]
