# Generated by Django 4.2.20 on 2025-09-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfranchise',
            name='registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
